apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EduardoThums/terraform-helm-test.git
    targetRevision: main
    path: ingress-nginx-app-of-apps/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
